# Generated by Django 3.2.10 on 2022-01-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_register_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
