# Generated by Django 3.2.10 on 2022-01-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20220101_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
