# Generated by Django 3.2.10 on 2021-12-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('number', models.CharField(max_length=50, unique=True)),
                ('driverName', models.CharField(max_length=255)),
                ('driverMobile', models.CharField(max_length=20, unique=True)),
                ('inchargeName', models.CharField(max_length=255)),
                ('inchargeContact', models.CharField(max_length=50, unique=True)),
                ('seats', models.IntegerField(default=45)),
            ],
        ),
        migrations.CreateModel(
            name='busStops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fee', models.IntegerField()),
                ('bus', models.ManyToManyField(to='CollegeAdmin.Bus')),
            ],
        ),
        migrations.CreateModel(
            name='busTimings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('bus', models.ManyToManyField(to='CollegeAdmin.Bus')),
                ('stop', models.ManyToManyField(to='CollegeAdmin.busStops')),
            ],
        ),
    ]
