# Generated by Django 3.2.10 on 2021-12-12 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bustimings',
            name='bus',
        ),
        migrations.AddField(
            model_name='bustimings',
            name='bus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CollegeAdmin.bus'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='bustimings',
            name='stop',
        ),
        migrations.AddField(
            model_name='bustimings',
            name='stop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CollegeAdmin.busstops'),
            preserve_default=False,
        ),
    ]
