# Generated by Django 3.2.10 on 2021-12-12 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CollegeAdmin', '0002_auto_20211212_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='busRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approvedStatus', models.BooleanField(default=False)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegeAdmin.busstops')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='busAllotmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatNumber', models.IntegerField()),
                ('paidAmount', models.IntegerField()),
                ('paymentStatus', models.BooleanField(default=False)),
                ('boardingPoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegeAdmin.busstops')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegeAdmin.bus')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
