# Generated by Django 3.2.10 on 2022-04-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeAdmin', '0004_alter_bustimings_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busallotmentdata',
            name='paidAmount',
            field=models.IntegerField(default=0),
        ),
    ]
