# Generated by Django 3.2.10 on 2022-04-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeAdmin', '0006_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='orderId',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentId',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='signature',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
